import type { DailyWeatherSeries } from "../model/DailyWeatherSeries.type";
import type { DailyWeatherSeriesRepository } from "../model/DailyWeatherSeriesRepository.interface";
import type { MainWeather } from "../model/MainWeather.type";
import type { Weather } from "../model/Weather.type";
import type {
  MainWeatherDTO,
  OpenWeatherOneCallResponse,
} from "./dto/OpenWeatherOneCallResponse.dto";

/**
 * @description OpenWeatherMap API를 사용하여 날씨 정보를 가져오는 리포지토리 구현체입니다.
 */
export const WeatherSeriesRepositoryMock: DailyWeatherSeriesRepository = {
  /**
   * @description 특정 위치와 시간 범위에 대한 날씨 시리즈를 가져옵니다.
   *
   * @remarks
   * **사용 중인 API**: [OpenWeather One Call API 3.0 - Current and Forecasts](https://openweathermap.org/api/one-call-3#current)
   * - 엔드포인트: `https://api.openweathermap.org/data/3.0/onecall`
   * - 제공 데이터: 현재 날씨 + 향후 48시간 hourly 예보
   *
   * **API 제약사항**:
   * - ⚠️ **과거 시간대 데이터는 조회할 수 없습니다.**
   * - 이 API는 현재 시간을 기준으로 향후 48시간 이내의 예보만 제공합니다.
   *
   * **대안**:
   * - 과거 시간대 데이터가 필요한 경우, [OpenWeather History API (Timemachine)](https://openweathermap.org/api/one-call-3#history)를 사용할 수 있습니다.
   * - 단, Timemachine API는 각 타임스탬프마다 개별 API 호출이 필요하여 비용 및 성능 문제가 있습니다.
   * - 현재 이 리포지토리에서는 History API를 사용하지 않습니다.
   *
   * @param location 날씨를 조회할 위치 (위경도 포함)
   * @param _options 추가 옵션 (시간을 언제 쪼갤지)
   * @returns 날씨 시리즈 데이터 (현재 온도, 최저/최고 온도, 시간대별 날씨 목록)
   */
  getDailyWeatherSeries: async ({
    location,
    weatherOptions,
  }): Promise<DailyWeatherSeries> => {
    await new Promise((resolve) => setTimeout(resolve, 500));

    const data: OpenWeatherOneCallResponse = {
      lat: 37.4754,
      lon: 126.9538,
      timezone: "Asia/Seoul",
      timezone_offset: 32400,
      current: {
        dt: 1768347642,
        sunrise: 1768344359,
        sunset: 1768379740,
        temp: -10.01,
        feels_like: -13.25,
        pressure: 1025,
        humidity: 70,
        dew_point: -13.97,
        uvi: 0.33,
        clouds: 0,
        visibility: 10000,
        wind_speed: 1.54,
        wind_deg: 50,
        weather: [
          {
            id: 800,
            main: "Clear",
            description: "clear sky",
            icon: "01d",
          },
        ],
      },
      hourly: [
        {
          dt: 1768345200,
          temp: -9.15,
          feels_like: -9.15,
          pressure: 1025,
          humidity: 59,
          dew_point: -15,
          uvi: 0,
          clouds: 2,
          visibility: 10000,
          wind_speed: 0.5,
          wind_deg: 1,
          wind_gust: 0.84,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768348800,
          temp: -10.01,
          feels_like: -10.01,
          pressure: 1025,
          humidity: 70,
          dew_point: -13.97,
          uvi: 0.33,
          clouds: 0,
          visibility: 10000,
          wind_speed: 0.32,
          wind_deg: 35,
          wind_gust: 0.55,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768352400,
          temp: -8.86,
          feels_like: -8.86,
          pressure: 1025,
          humidity: 58,
          dew_point: -14.91,
          uvi: 0.78,
          clouds: 1,
          visibility: 10000,
          wind_speed: 0.15,
          wind_deg: 169,
          wind_gust: 0.43,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768356000,
          temp: -7.29,
          feels_like: -7.29,
          pressure: 1025,
          humidity: 46,
          dew_point: -15.93,
          uvi: 1.33,
          clouds: 2,
          visibility: 10000,
          wind_speed: 0.53,
          wind_deg: 40,
          wind_gust: 0.33,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768359600,
          temp: -5.37,
          feels_like: -5.37,
          pressure: 1025,
          humidity: 34,
          dew_point: -17.39,
          uvi: 1.7,
          clouds: 2,
          visibility: 10000,
          wind_speed: 1.22,
          wind_deg: 264,
          wind_gust: 1.72,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768363200,
          temp: -3.22,
          feels_like: -3.22,
          pressure: 1025,
          humidity: 24,
          dew_point: -19.13,
          uvi: 1.68,
          clouds: 2,
          visibility: 10000,
          wind_speed: 1.2,
          wind_deg: 267,
          wind_gust: 1.88,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768366800,
          temp: -0.99,
          feels_like: -0.99,
          pressure: 1024,
          humidity: 15,
          dew_point: -24.07,
          uvi: 1.37,
          clouds: 3,
          visibility: 10000,
          wind_speed: 0.95,
          wind_deg: 277,
          wind_gust: 1.58,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768370400,
          temp: -0.69,
          feels_like: -0.69,
          pressure: 1023,
          humidity: 19,
          dew_point: -21.35,
          uvi: 0.83,
          clouds: 3,
          visibility: 10000,
          wind_speed: 0.34,
          wind_deg: 188,
          wind_gust: 1.47,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768374000,
          temp: -0.38,
          feels_like: -0.38,
          pressure: 1022,
          humidity: 22,
          dew_point: -19.39,
          uvi: 0.32,
          clouds: 17,
          visibility: 10000,
          wind_speed: 0.74,
          wind_deg: 134,
          wind_gust: 1.37,
          weather: [
            {
              id: 801,
              main: "Clouds",
              description: "few clouds",
              icon: "02d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768377600,
          temp: -0.37,
          feels_like: -0.37,
          pressure: 1022,
          humidity: 25,
          dew_point: -18.08,
          uvi: 0,
          clouds: 15,
          visibility: 10000,
          wind_speed: 1.03,
          wind_deg: 115,
          wind_gust: 1.62,
          weather: [
            {
              id: 801,
              main: "Clouds",
              description: "few clouds",
              icon: "02d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768381200,
          temp: -0.55,
          feels_like: -2.72,
          pressure: 1022,
          humidity: 24,
          dew_point: -18.61,
          uvi: 0,
          clouds: 42,
          visibility: 10000,
          wind_speed: 1.72,
          wind_deg: 92,
          wind_gust: 2.92,
          weather: [
            {
              id: 802,
              main: "Clouds",
              description: "scattered clouds",
              icon: "03n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768384800,
          temp: -0.48,
          feels_like: -3.43,
          pressure: 1021,
          humidity: 22,
          dew_point: -19.24,
          uvi: 0,
          clouds: 56,
          visibility: 10000,
          wind_speed: 2.35,
          wind_deg: 82,
          wind_gust: 4.3,
          weather: [
            {
              id: 803,
              main: "Clouds",
              description: "broken clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768388400,
          temp: -0.27,
          feels_like: -2.78,
          pressure: 1020,
          humidity: 23,
          dew_point: -18.49,
          uvi: 0,
          clouds: 65,
          visibility: 10000,
          wind_speed: 2.01,
          wind_deg: 91,
          wind_gust: 4.18,
          weather: [
            {
              id: 803,
              main: "Clouds",
              description: "broken clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768392000,
          temp: -0.12,
          feels_like: -2.63,
          pressure: 1019,
          humidity: 25,
          dew_point: -17.57,
          uvi: 0,
          clouds: 71,
          visibility: 10000,
          wind_speed: 2.03,
          wind_deg: 87,
          wind_gust: 4.12,
          weather: [
            {
              id: 803,
              main: "Clouds",
              description: "broken clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768395600,
          temp: 0.17,
          feels_like: -2.55,
          pressure: 1018,
          humidity: 27,
          dew_point: -16.56,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 2.25,
          wind_deg: 83,
          wind_gust: 4.32,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768399200,
          temp: 0.32,
          feels_like: -2.25,
          pressure: 1018,
          humidity: 28,
          dew_point: -15.79,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 2.14,
          wind_deg: 84,
          wind_gust: 4.07,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768402800,
          temp: 0.52,
          feels_like: -1.95,
          pressure: 1017,
          humidity: 30,
          dew_point: -14.85,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 2.08,
          wind_deg: 84,
          wind_gust: 3.9,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768406400,
          temp: 0.7,
          feels_like: -1.7,
          pressure: 1016,
          humidity: 33,
          dew_point: -13.75,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 2.05,
          wind_deg: 90,
          wind_gust: 3.85,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768410000,
          temp: 1.08,
          feels_like: -0.69,
          pressure: 1015,
          humidity: 42,
          dew_point: -10.2,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 1.61,
          wind_deg: 84,
          wind_gust: 3.47,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768413600,
          temp: 1.28,
          feels_like: -0.51,
          pressure: 1015,
          humidity: 47,
          dew_point: -8.8,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 1.65,
          wind_deg: 97,
          wind_gust: 3.26,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768417200,
          temp: 1.59,
          feels_like: -0.27,
          pressure: 1014,
          humidity: 55,
          dew_point: -6.38,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 1.73,
          wind_deg: 92,
          wind_gust: 2.95,
          weather: [
            {
              id: 500,
              main: "Rain",
              description: "light rain",
              icon: "10n",
            },
          ],
          pop: 0.2,
          rain: {
            "1h": 0.1,
          },
        },
        {
          dt: 1768420800,
          temp: 1.78,
          feels_like: -0.09,
          pressure: 1013,
          humidity: 59,
          dew_point: -5.31,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 1.76,
          wind_deg: 99,
          wind_gust: 3.01,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768424400,
          temp: 2.06,
          feels_like: 0.26,
          pressure: 1013,
          humidity: 65,
          dew_point: -3.81,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 1.74,
          wind_deg: 109,
          wind_gust: 2.41,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768428000,
          temp: 2.36,
          feels_like: 0.57,
          pressure: 1013,
          humidity: 71,
          dew_point: -2.36,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 1.77,
          wind_deg: 128,
          wind_gust: 2.87,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768431600,
          temp: 2.84,
          feels_like: 1.24,
          pressure: 1013,
          humidity: 80,
          dew_point: -0.2,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 1.68,
          wind_deg: 161,
          wind_gust: 4.22,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768435200,
          temp: 3.51,
          feels_like: 2.02,
          pressure: 1013,
          humidity: 91,
          dew_point: 2.23,
          uvi: 0.3,
          clouds: 100,
          visibility: 10000,
          wind_speed: 1.67,
          wind_deg: 184,
          wind_gust: 3.83,
          weather: [
            {
              id: 804,
              main: "Clouds",
              description: "overcast clouds",
              icon: "04d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768438800,
          temp: 4.74,
          feels_like: 3.14,
          pressure: 1014,
          humidity: 94,
          dew_point: 3.94,
          uvi: 0.77,
          clouds: 71,
          visibility: 10000,
          wind_speed: 1.93,
          wind_deg: 224,
          wind_gust: 7.59,
          weather: [
            {
              id: 803,
              main: "Clouds",
              description: "broken clouds",
              icon: "04d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768442400,
          temp: 6.19,
          feels_like: 3.91,
          pressure: 1015,
          humidity: 86,
          dew_point: 4.08,
          uvi: 1.29,
          clouds: 72,
          visibility: 10000,
          wind_speed: 3.04,
          wind_deg: 260,
          wind_gust: 7.09,
          weather: [
            {
              id: 803,
              main: "Clouds",
              description: "broken clouds",
              icon: "04d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768446000,
          temp: 7.16,
          feels_like: 4.62,
          pressure: 1014,
          humidity: 66,
          dew_point: 1.35,
          uvi: 1.65,
          clouds: 63,
          visibility: 10000,
          wind_speed: 3.8,
          wind_deg: 266,
          wind_gust: 7.05,
          weather: [
            {
              id: 803,
              main: "Clouds",
              description: "broken clouds",
              icon: "04d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768449600,
          temp: 7.56,
          feels_like: 4.85,
          pressure: 1014,
          humidity: 58,
          dew_point: -0.08,
          uvi: 1.73,
          clouds: 48,
          visibility: 10000,
          wind_speed: 4.32,
          wind_deg: 269,
          wind_gust: 7.04,
          weather: [
            {
              id: 802,
              main: "Clouds",
              description: "scattered clouds",
              icon: "03d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768453200,
          temp: 7.63,
          feels_like: 4.81,
          pressure: 1014,
          humidity: 55,
          dew_point: -0.68,
          uvi: 1.4,
          clouds: 39,
          visibility: 10000,
          wind_speed: 4.57,
          wind_deg: 266,
          wind_gust: 7.38,
          weather: [
            {
              id: 802,
              main: "Clouds",
              description: "scattered clouds",
              icon: "03d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768456800,
          temp: 7.32,
          feels_like: 4.4,
          pressure: 1014,
          humidity: 56,
          dew_point: -0.84,
          uvi: 0.87,
          clouds: 33,
          visibility: 10000,
          wind_speed: 4.64,
          wind_deg: 267,
          wind_gust: 7.29,
          weather: [
            {
              id: 802,
              main: "Clouds",
              description: "scattered clouds",
              icon: "03d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768460400,
          temp: 6.56,
          feels_like: 3.42,
          pressure: 1015,
          humidity: 59,
          dew_point: -0.84,
          uvi: 0.37,
          clouds: 2,
          visibility: 10000,
          wind_speed: 4.7,
          wind_deg: 269,
          wind_gust: 7.28,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768464000,
          temp: 5.65,
          feels_like: 2.53,
          pressure: 1015,
          humidity: 65,
          dew_point: -0.41,
          uvi: 0,
          clouds: 4,
          visibility: 10000,
          wind_speed: 4.24,
          wind_deg: 268,
          wind_gust: 7.45,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768467600,
          temp: 4.69,
          feels_like: 1.65,
          pressure: 1016,
          humidity: 72,
          dew_point: 0.13,
          uvi: 0,
          clouds: 4,
          visibility: 10000,
          wind_speed: 3.71,
          wind_deg: 264,
          wind_gust: 7.55,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768471200,
          temp: 4.25,
          feels_like: 1.23,
          pressure: 1017,
          humidity: 73,
          dew_point: -0.03,
          uvi: 0,
          clouds: 4,
          visibility: 10000,
          wind_speed: 3.53,
          wind_deg: 263,
          wind_gust: 7.67,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768474800,
          temp: 3.93,
          feels_like: 0.98,
          pressure: 1018,
          humidity: 72,
          dew_point: -0.53,
          uvi: 0,
          clouds: 3,
          visibility: 10000,
          wind_speed: 3.33,
          wind_deg: 268,
          wind_gust: 7.23,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768478400,
          temp: 3.41,
          feels_like: 0.89,
          pressure: 1018,
          humidity: 73,
          dew_point: -0.94,
          uvi: 0,
          clouds: 3,
          visibility: 10000,
          wind_speed: 2.64,
          wind_deg: 279,
          wind_gust: 5.93,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768482000,
          temp: 2.71,
          feels_like: 0.37,
          pressure: 1019,
          humidity: 75,
          dew_point: -1.2,
          uvi: 0,
          clouds: 5,
          visibility: 10000,
          wind_speed: 2.31,
          wind_deg: 289,
          wind_gust: 4.83,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768485600,
          temp: 1.89,
          feels_like: -0.27,
          pressure: 1020,
          humidity: 74,
          dew_point: -2.23,
          uvi: 0,
          clouds: 5,
          visibility: 10000,
          wind_speed: 2.01,
          wind_deg: 303,
          wind_gust: 4.69,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768489200,
          temp: 1.31,
          feels_like: 1.31,
          pressure: 1020,
          humidity: 72,
          dew_point: -3.21,
          uvi: 0,
          clouds: 5,
          visibility: 10000,
          wind_speed: 1.26,
          wind_deg: 305,
          wind_gust: 3.74,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768492800,
          temp: 0.92,
          feels_like: 0.92,
          pressure: 1020,
          humidity: 71,
          dew_point: -3.73,
          uvi: 0,
          clouds: 4,
          visibility: 10000,
          wind_speed: 0.78,
          wind_deg: 275,
          wind_gust: 1.62,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768496400,
          temp: 0.65,
          feels_like: 0.65,
          pressure: 1020,
          humidity: 71,
          dew_point: -3.98,
          uvi: 0,
          clouds: 3,
          visibility: 10000,
          wind_speed: 0.58,
          wind_deg: 255,
          wind_gust: 0.73,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768500000,
          temp: 0.45,
          feels_like: 0.45,
          pressure: 1021,
          humidity: 70,
          dew_point: -4.26,
          uvi: 0,
          clouds: 3,
          visibility: 10000,
          wind_speed: 0.85,
          wind_deg: 284,
          wind_gust: 0.96,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768503600,
          temp: 0.19,
          feels_like: 0.19,
          pressure: 1021,
          humidity: 70,
          dew_point: -4.48,
          uvi: 0,
          clouds: 0,
          visibility: 10000,
          wind_speed: 0.88,
          wind_deg: 301,
          wind_gust: 0.96,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768507200,
          temp: -0.03,
          feels_like: -0.03,
          pressure: 1021,
          humidity: 71,
          dew_point: -4.65,
          uvi: 0,
          clouds: 0,
          visibility: 10000,
          wind_speed: 0.86,
          wind_deg: 332,
          wind_gust: 0.91,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768510800,
          temp: -0.19,
          feels_like: -0.19,
          pressure: 1021,
          humidity: 71,
          dew_point: -4.68,
          uvi: 0,
          clouds: 0,
          visibility: 10000,
          wind_speed: 0.82,
          wind_deg: 337,
          wind_gust: 0.87,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
        {
          dt: 1768514400,
          temp: -0.25,
          feels_like: -0.25,
          pressure: 1022,
          humidity: 72,
          dew_point: -4.65,
          uvi: 0,
          clouds: 0,
          visibility: 10000,
          wind_speed: 0.44,
          wind_deg: 344,
          wind_gust: 0.52,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01n",
            },
          ],
          pop: 0,
        },
      ],
      daily: [
        {
          dt: 1768359600,
          sunrise: 1768344359,
          sunset: 1768379740,
          moonrise: 1768330740,
          moonset: 1768364880,
          moon_phase: 0.85,

          temp: {
            day: -5.37,
            min: -10.01,
            max: 0.32,
            night: 0.32,
            eve: -0.55,
            morn: -7.67,
          },
          feels_like: {
            day: -5.37,
            night: -2.25,
            eve: -2.72,
            morn: -7.67,
          },
          pressure: 1025,
          humidity: 34,
          dew_point: -17.39,
          wind_speed: 3.78,
          wind_deg: 304,
          wind_gust: 6.76,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          clouds: 2,
          pop: 0,
          uvi: 1.7,
        },
        {
          dt: 1768446000,
          sunrise: 1768430742,
          sunset: 1768466201,
          moonrise: 1768420680,
          moonset: 1768453740,
          moon_phase: 0.88,

          temp: {
            day: 7.16,
            min: 0.52,
            max: 7.63,
            night: 1.89,
            eve: 4.69,
            morn: 2.06,
          },
          feels_like: {
            day: 4.62,
            night: -0.27,
            eve: 1.65,
            morn: 0.26,
          },
          pressure: 1014,
          humidity: 66,
          dew_point: 1.35,
          wind_speed: 4.7,
          wind_deg: 269,
          wind_gust: 7.67,
          weather: [
            {
              id: 500,
              main: "Rain",
              description: "light rain",
              icon: "10d",
            },
          ],
          clouds: 63,
          pop: 0.2,
          rain: 0.1,
          uvi: 1.73,
        },
        {
          dt: 1768532400,
          sunrise: 1768517123,
          sunset: 1768552662,
          moonrise: 1768510500,
          moonset: 1768543080,
          moon_phase: 0.91,

          temp: {
            day: 3.94,
            min: -0.25,
            max: 6.22,
            night: 2.6,
            eve: 5.08,
            morn: -0.19,
          },
          feels_like: {
            day: 3.94,
            night: 2.6,
            eve: 3.81,
            morn: -0.19,
          },
          pressure: 1022,
          humidity: 44,
          dew_point: -6.97,
          wind_speed: 1.76,
          wind_deg: 289,
          wind_gust: 3.74,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          clouds: 0,
          pop: 0,
          uvi: 2.06,
        },
        {
          dt: 1768618800,
          sunrise: 1768603502,
          sunset: 1768639124,
          moonrise: 1768600020,
          moonset: 1768632840,
          moon_phase: 0.95,

          temp: {
            day: 3.53,
            min: -0.32,
            max: 5.75,
            night: 3.91,
            eve: 5.23,
            morn: 0.22,
          },
          feels_like: {
            day: 2.2,
            night: 3.91,
            eve: 5.23,
            morn: -1.27,
          },
          pressure: 1024,
          humidity: 27,
          dew_point: -13.68,
          wind_speed: 1.68,
          wind_deg: 354,
          wind_gust: 2.5,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          clouds: 0,
          pop: 0,
          uvi: 2.33,
        },
        {
          dt: 1768705200,
          sunrise: 1768689879,
          sunset: 1768725587,
          moonrise: 1768689120,
          moonset: 1768722960,
          moon_phase: 0.98,

          temp: {
            day: 4.66,
            min: 1.72,
            max: 5.11,
            night: 2.48,
            eve: 2.68,
            morn: 1.72,
          },
          feels_like: {
            day: 4.66,
            night: 2.48,
            eve: 2.68,
            morn: 0.44,
          },
          pressure: 1023,
          humidity: 53,
          dew_point: -4.11,
          wind_speed: 1.86,
          wind_deg: 339,
          wind_gust: 2.43,
          weather: [
            {
              id: 600,
              main: "Snow",
              description: "light snow",
              icon: "13d",
            },
          ],
          clouds: 82,
          pop: 1,
          snow: 1.7,
          uvi: 1.11,
        },
        {
          dt: 1768791600,
          sunrise: 1768776255,
          sunset: 1768812051,
          moonrise: 1768777800,
          moonset: 1768813200,
          moon_phase: 0,

          temp: {
            day: -0.69,
            min: -7.13,
            max: 2.07,
            night: -7.13,
            eve: -5.56,
            morn: 0.28,
          },
          feels_like: {
            day: -6.19,
            night: -14.06,
            eve: -12.56,
            morn: -3.16,
          },
          pressure: 1025,
          humidity: 37,
          dew_point: -13.47,
          wind_speed: 6.25,
          wind_deg: 308,
          wind_gust: 9.33,
          weather: [
            {
              id: 616,
              main: "Snow",
              description: "rain and snow",
              icon: "13d",
            },
          ],
          clouds: 72,
          pop: 1,
          rain: 1.2,
          snow: 1.23,
          uvi: 2,
        },
        {
          dt: 1768878000,
          sunrise: 1768862628,
          sunset: 1768898515,
          moonrise: 1768866120,
          moonset: 1768903560,
          moon_phase: 0.04,

          temp: {
            day: -5.63,
            min: -8.67,
            max: -4.88,
            night: -8.18,
            eve: -6.42,
            morn: -8.36,
          },
          feels_like: {
            day: -10.5,
            night: -15.09,
            eve: -12.91,
            morn: -13.64,
          },
          pressure: 1029,
          humidity: 20,
          dew_point: -25.21,
          wind_speed: 5.16,
          wind_deg: 313,
          wind_gust: 7.72,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          clouds: 6,
          pop: 0,
          uvi: 2,
        },
        {
          dt: 1768964400,
          sunrise: 1768948999,
          sunset: 1768984979,
          moonrise: 1768954260,
          moonset: 1768993860,
          moon_phase: 0.07,

          temp: {
            day: -7.98,
            min: -10.6,
            max: -6.39,
            night: -8.98,
            eve: -7.27,
            morn: -10.6,
          },
          feels_like: {
            day: -14.98,
            night: -15.98,
            eve: -14.27,
            morn: -17.52,
          },
          pressure: 1030,
          humidity: 26,
          dew_point: -24.42,
          wind_speed: 5.63,
          wind_deg: 307,
          wind_gust: 10.98,
          weather: [
            {
              id: 800,
              main: "Clear",
              description: "clear sky",
              icon: "01d",
            },
          ],
          clouds: 0,
          pop: 0,
          uvi: 2,
        },
      ],
    };

    const currentTemperature = {
      value: data.current.temp,
      unit: "C" as const,
    };

    // 오늘에 해당하는 hourly 데이터만 필터링
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const tomorrow = new Date(today);
    tomorrow.setDate(today.getDate() + 1);

    const startTimestamp = Math.floor(today.getTime() / 1000);
    const endTimestamp = Math.floor(tomorrow.getTime() / 1000);

    const filteredHourly = data.hourly.filter(
      (h) => h.dt >= startTimestamp && h.dt <= endTimestamp,
    );

    // timeUnit 기반 재샘플링
    const timeUnitSeconds = weatherOptions?.timeUnit ?? 3600; // 기본 1시간 단위
    const resampledWeathers: Weather[] = [];

    const firstHourlyDt = data.hourly[0]?.dt ?? startTimestamp;
    const sliceStart = Math.max(startTimestamp, firstHourlyDt);

    for (
      let sliceTime = sliceStart + timeUnitSeconds;
      sliceTime <= endTimestamp;
      sliceTime += timeUnitSeconds
    ) {
      // sliceTime과 가장 가까운 데이터 찾기
      const closest = filteredHourly.reduce<null | (typeof filteredHourly)[0]>(
        (prev, curr) => {
          if (!prev) return curr;
          return Math.abs(curr.dt - sliceTime) < Math.abs(prev.dt - sliceTime)
            ? curr
            : prev;
        },
        null,
      );

      if (closest) {
        resampledWeathers.push({
          dt: closest.dt,
          temperature: { value: closest.temp, unit: "C" },
          feels_like_temperature: { value: closest.feels_like, unit: "C" },
          mainWeather: mapMainWeather(closest.weather[0].main),
        });
      }
    }

    // 최저/최고 온도 계산 (현재 온도 포함)
    const temperatureDataSource = [
      data.current,
      ...resampledWeathers.map((w) => ({ temp: w.temperature.value })),
    ];
    const temperatures = temperatureDataSource.map((h) => h.temp);

    const minTemperature = {
      value: Math.min(...temperatures),
      unit: "C" as const,
    };
    const maxTemperature = {
      value: Math.max(...temperatures),
      unit: "C" as const,
    };

    return {
      currentTemperature,
      minTemperature,
      maxTemperature,
      weathers: resampledWeathers,
      mainWeather: mapMainWeather(data.daily[0].weather[0].main),
      feelsLikeTemperature: { value: data.daily[0].feels_like.day, unit: "C" },
      rainProbability: data.daily[0].pop,
    };
  },
};

/**
 * @description MainWeatherDTO → 도메인 MainWeather로 변환
 * @param dto OpenWeather에서 받은 날씨 그룹
 * @returns 도메인에서 사용하는 MainWeather
 */
const mapMainWeather = (dto: MainWeatherDTO): MainWeather => {
  switch (dto) {
    case "Clear":
    case "Clouds":
    case "Rain":
    case "Snow":
    case "Thunderstorm":
    case "Drizzle":
      return dto; // 도메인에 있는 값 그대로 반환
    default:
      return "Clear"; // 도메인에 없는 값은 기본값
  }
};
